# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('paper_date', models.DateField()),
                ('paper_title', models.CharField(max_length=1000)),
                ('conflict', models.TextField()),
            ],
        ),
    ]
