# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='author_affiliation',
            field=models.CharField(default='a', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='paper_title',
            field=models.CharField(max_length=2000),
        ),
    ]
