# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coi', '0002_auto_20161026_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='author_affiliation',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
