# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coi', '0003_auto_20161026_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='paper_url',
            field=models.URLField(default='http://localhost'),
            preserve_default=False,
        ),
    ]
